# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    calculator.operations.divide:
        class: 'App\Calculator\Arithmetic\Operation\Divide'
    calculator.operations.multiply:
        class: 'App\Calculator\Arithmetic\Operation\Multiply'
    calculator.operations.subtract:
        class: 'App\Calculator\Arithmetic\Operation\Subtract'
    calculator.operations.sum:
        class: 'App\Calculator\Arithmetic\Operation\Sum'
            
    App\Calculator\CalculatorInterface:
        class: 'App\Calculator\Arithmetic\ArithmeticCalculator'
        bind:
            $operationsSupported:
                - '@calculator.operations.divide'
                - '@calculator.operations.multiply'
                - '@calculator.operations.subtract'
                - '@calculator.operations.sum'
